language: node_js
node_js:
    - node
    - lts/*
notifications:
  slack:
    secure: bBDo4VltbneUa7vPAlxJE6gAV+MgWLgOz/bL1/QUnsYbaeEanAe60L+GTlE1j9stopWdEg2LG39LKnu/9rrG/oDmK0EIYVHq3MXBxdVpQEvcuQ5i+lZCEcg8eLOiCyLlQ9I3LYrznhN8Pn8LP/RfGNeLWk5k9Dy4ybzruQ2d6D3H1Y0tHdgrZb9FtKRPHQ/mrIdh+83+/D+wX/Td3fT53Gzv7qN64bogLVnymGJNF8IUHoqYhGzCZpq4VKqoypWn2eqWjWsUhDqRUAUFmYTmKzJVDKziTho0vVQ9OjnDIEjzngNJIeetbj2qHv+gtpSXw7zSnwN3kMIzRH7BMN8u7HGAchp73Cj9RPxlGW8b+/Ho/bSYsm4P4lCUbXd8XcNRMRuZA3a6nfkqc6ZSkbqYczpFPaW05PrJ7g6jOpd7H9QoSkcKyLC3QnBe3WMLYp3v9XoaQKygKK2Qby35DvvculnTkqeqkKHmEfOzZ8aB9EwaOrfp4syymmwwwLxp5kFZd10tPNlEtLcAA+TAm2W0EqOl90Epadba5zylqIyNf9rRN1HzfAC7ob8pXtNnMj5mWEHwvIYB5yCMGz67o2oHioJ1OvaRmt/GUwHzRJo0ffUK0hVpmcZANbJdb0sqvyC4LU0MeCQaynbjrIyqDYt6N4mrRu6Ajmc3qxI4YyMv2CI=
